### ISSUE TITLE
Exemplo contém erro no nome do resource

### ISSUE THREAD

**Issue by jbragagnolo** [tsuru/terraform-provider-rpaas#10]
Na [doc](https://registry.terraform.io/providers/tsuru/rpaas/latest/docs/resources/file) o exemplo está com nome do resource "foo.txt" `resource "rpaas_file" "foo.txt" `, porém este não deveria conter `.`(ponto).

```
Error: Invalid resource name
   on rpaas.tf line 76, in resource "rpaas_file" "redirects-home-nginx.inc":
   76: resource "rpaas_file" "redirects-home-nginx.inc" {
 
 A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.
```

**Comment by tcarreira** [comment]
fixed with 6c14b0344eb05194dd470fe104659820aff90504

Thanks @jbragagnolo  ❤️

**Comment by tcarreira** [comment]
updated: [resource rpaas_file](https://registry.terraform.io/providers/tsuru/rpaas/latest/docs/resources/file)
