### ISSUE TITLE
Erro no update do resource rpaas_file

### ISSUE THREAD

**Issue by juliolustosa** [tsuru/terraform-provider-rpaas#13]
Quando tento enviar um arquivo com o conteúdo diferente com o mesmo nome de arquivo.

`Error: Unable to upsert file "redirects-nginx.inc" for instance qa: rpaasv2: unexpected status code: 409 Conflict, detail: {"message":"file already exists"}`

**Comment by tcarreira** [comment]
Este conflito acontece se o nome do resource mudar.
Aí o terraform não tem forma de saber que se trata do mesmo recurso, e se o create do novo recurso acontecer antes do delete do recurso antigo, dá esse conflito.

Não é um bug no provider, mas sim na forma como o resource rpaas_file está sendo usado.
