### ISSUE TITLE
Erro no resource_rpaas_file ao fazer upload de arquivo grande

### ISSUE THREAD

**Issue by juliolustosa** [tsuru/terraform-provider-rpaas#20]
Erro ao tentar fazer upload de um arquivo grande com muitas regras.

`{"message":"file \"redirect.conf\" exceeds the max size of 1048576 bytes"}`

**Comment by tcarreira** [comment]
Não é um bug do provider, é uma feature da API, limite máximo de 1MB por arquivo.

**Comment by juliolustosa** [comment]
@tcarreira temos arquivos com muitos registros que precisamos que sejam feito upload. O limite de 1mb de upload é muito baixo, poderia ser pelo menos 10mb.

**Comment by tcarreira** [comment]
Não está relacionado com este provider. A limitação é na API.

Mas a resposta mais provável é "Não". 
A funcionalidade é implementada com ConfigMap, e pela [documentação](https://kubernetes.io/docs/concepts/configuration/configmap/#motivation):
> The data stored in a ConfigMap cannot exceed 1 MiB.
