### ISSUE TITLE
Sugestão liberação de ACL por cluster local no resource_rpaas_acl

### ISSUE THREAD

**Issue by juliolustosa** [tsuru/terraform-provider-rpaas#21]
Através da opção host não estou conseguindo liberar ACL do tipo
`.svc.cluster.local`

**Comment by tcarreira** [comment]
Sem mais dados não consigo confirmar, mas acho mais provável que o problema seja na [rpaas API](https://github.com/tsuru/rpaas-operator) e não no provider Terraform.
